// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VendorRisk.Infrastructure.Persistence;

#nullable disable

namespace VendorRisk.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VendorRisk.Domain.Entities.RiskCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_risk_categories");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_risk_categories_code");

                    b.ToTable("risk_categories", (string)null);
                });

            modelBuilder.Entity("VendorRisk.Domain.Entities.RiskFactorEdge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChildFactorId")
                        .HasColumnType("integer")
                        .HasColumnName("child_factor_id");

                    b.Property<int>("ParentFactorId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_factor_id");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_risk_factor_edges");

                    b.HasIndex("ChildFactorId")
                        .HasDatabaseName("ix_risk_factor_edges_child_factor_id");

                    b.HasIndex("ParentFactorId", "ChildFactorId")
                        .IsUnique()
                        .HasDatabaseName("ix_risk_factor_edges_parent_factor_id_child_factor_id");

                    b.ToTable("risk_factor_edges", (string)null);
                });

            modelBuilder.Entity("VendorRisk.Domain.Entities.RiskFactorNode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_risk_factors");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_risk_factors_category_id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_risk_factors_code");

                    b.ToTable("risk_factors", (string)null);
                });

            modelBuilder.Entity("VendorRisk.Domain.Entities.VendorProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FinancialHealth")
                        .HasColumnType("integer")
                        .HasColumnName("financial_health");

                    b.Property<int>("MajorIncidents")
                        .HasColumnType("integer")
                        .HasColumnName("major_incidents");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<List<string>>("SecurityCerts")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("security_certs");

                    b.Property<int>("SlaUptime")
                        .HasColumnType("integer")
                        .HasColumnName("sla_uptime");

                    b.HasKey("Id")
                        .HasName("pk_vendors");

                    b.ToTable("vendors", (string)null);
                });

            modelBuilder.Entity("VendorRisk.Domain.Entities.RiskFactorEdge", b =>
                {
                    b.HasOne("VendorRisk.Domain.Entities.RiskFactorNode", "Child")
                        .WithMany()
                        .HasForeignKey("ChildFactorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_risk_factor_edges_risk_factors_child_factor_id");

                    b.HasOne("VendorRisk.Domain.Entities.RiskFactorNode", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentFactorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_risk_factor_edges_risk_factors_parent_factor_id");

                    b.Navigation("Child");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("VendorRisk.Domain.Entities.RiskFactorNode", b =>
                {
                    b.HasOne("VendorRisk.Domain.Entities.RiskCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_risk_factors_risk_categories_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("VendorRisk.Domain.Entities.VendorProfile", b =>
                {
                    b.OwnsOne("VendorRisk.Domain.Entities.VendorDocuments", "Documents", b1 =>
                        {
                            b1.Property<int>("VendorProfileId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<bool?>("ContractValid")
                                .HasColumnType("boolean")
                                .HasColumnName("contract_valid");

                            b1.Property<bool?>("PentestReportValid")
                                .HasColumnType("boolean")
                                .HasColumnName("pentest_report_valid");

                            b1.Property<bool?>("PrivacyPolicyValid")
                                .HasColumnType("boolean")
                                .HasColumnName("privacy_policy_valid");

                            b1.HasKey("VendorProfileId");

                            b1.ToTable("vendors");

                            b1.WithOwner()
                                .HasForeignKey("VendorProfileId")
                                .HasConstraintName("fk_vendors_vendors_id");
                        });

                    b.Navigation("Documents")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
